<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<h6 class="heading"><span class="type">Paragraph</span></h6>
<div class="para">As it turns out, we actually want to stop the execution of the program if any of the generated exceptions come up. This is handled by simply putting the command <code class="code-inline tex2jax_ignore">
                    raise</code> in the <code class="code-inline tex2jax_ignore">except:...</code> block without any argument. This causes the exception which brought about the problem to be passed up to the next level; this could be a <code class="code-inline tex2jax_ignore">try:... except:...</code> block in a calling function, or it could be the main execution loop of Python. In the latter case, this causes an error and stops execution of your code!</div>
<span class="incontext"><a href="sec-linalg-matproj.html#p-534" class="internal">in-context</a></span>
</body>
</html>
